[2024-10-21T00:57:51.801+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: twitch_data_pipeline.extract_stream_data manual__2024-10-21T00:57:50.434640+00:00 [queued]>
[2024-10-21T00:57:51.809+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: twitch_data_pipeline.extract_stream_data manual__2024-10-21T00:57:50.434640+00:00 [queued]>
[2024-10-21T00:57:51.809+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2024-10-21T00:57:51.809+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2024-10-21T00:57:51.809+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2024-10-21T00:57:51.820+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): extract_stream_data> on 2024-10-21 00:57:50.434640+00:00
[2024-10-21T00:57:51.829+0000] {standard_task_runner.py:55} INFO - Started process 1389 to run task
[2024-10-21T00:57:51.833+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'twitch_data_pipeline', 'extract_stream_data', 'manual__2024-10-21T00:57:50.434640+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmphgz_z7ir']
[2024-10-21T00:57:51.833+0000] {standard_task_runner.py:83} INFO - Job 5: Subtask extract_stream_data
[2024-10-21T00:57:51.888+0000] {task_command.py:389} INFO - Running <TaskInstance: twitch_data_pipeline.extract_stream_data manual__2024-10-21T00:57:50.434640+00:00 [running]> on host fba2d95bf80f
[2024-10-21T00:57:51.955+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=leo-coltri
AIRFLOW_CTX_DAG_ID=twitch_data_pipeline
AIRFLOW_CTX_TASK_ID=extract_stream_data
AIRFLOW_CTX_EXECUTION_DATE=2024-10-21T00:57:50.434640+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-10-21T00:57:50.434640+00:00
[2024-10-21T00:57:51.957+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/scripts/data_extraction.py", line 16, in extract_stream_data
    producer = create_kafka_producer()
  File "/opt/airflow/dags/scripts/data_extraction.py", line 8, in create_kafka_producer
    return KafkaProducer(bootstrap_servers=['https://9021-leocoltri-twitchkafkael-yu05xt98t2r.ws-us116.gitpod.io'])
  File "/home/airflow/.local/lib/python3.7/site-packages/kafka/producer/kafka.py", line 383, in __init__
    **self.config)
  File "/home/airflow/.local/lib/python3.7/site-packages/kafka/client_async.py", line 210, in __init__
    self.cluster = ClusterMetadata(**self.config)
  File "/home/airflow/.local/lib/python3.7/site-packages/kafka/cluster.py", line 67, in __init__
    self._bootstrap_brokers = self._generate_bootstrap_brokers()
  File "/home/airflow/.local/lib/python3.7/site-packages/kafka/cluster.py", line 72, in _generate_bootstrap_brokers
    bootstrap_hosts = collect_hosts(self.config['bootstrap_servers'])
  File "/home/airflow/.local/lib/python3.7/site-packages/kafka/conn.py", line 1497, in collect_hosts
    host, port, afi = get_ip_port_afi(host_port)
  File "/home/airflow/.local/lib/python3.7/site-packages/kafka/conn.py", line 1478, in get_ip_port_afi
    port = int(port)
ValueError: invalid literal for int() with base 10: '//9021-leocoltri-twitchkafkael-yu05xt98t2r.ws-us116.gitpod.io'
[2024-10-21T00:57:51.967+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=twitch_data_pipeline, task_id=extract_stream_data, execution_date=20241021T005750, start_date=20241021T005751, end_date=20241021T005751
[2024-10-21T00:57:51.976+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 5 for task extract_stream_data (invalid literal for int() with base 10: '//9021-leocoltri-twitchkafkael-yu05xt98t2r.ws-us116.gitpod.io'; 1389)
[2024-10-21T00:57:52.004+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2024-10-21T00:57:52.021+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
